apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: rt-workstation
  namespace: metallb-system
spec:
  addresses:
    - 10.0.40.147-10.0.40.148
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: rt-workstation-l2advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - rt-workstation
--- 
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: rt-workstation-sa
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rt-workstation-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ocs-storagecluster-cephfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rt-workstation-deployment
  labels:
    app: rt-workstation-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rt-workstation-app
  template:
    metadata:
      labels:
        app: rt-workstation-app
    spec:
      serviceAccountName: rt-workstation-sa
      containers:
        - name: rt-workstation-container
          image:  quay.io/rthollibm/workstation:1.0
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "4Gi"
          volumeMounts:
            - mountPath: "/data"
              name: data-volume
          imagePullPolicy: Always
          securityContext:   
            capabilities:   
              add:         
                - SYS_CHROOT
                - SYS_ADMIN
                - NET_ADMIN
                - NET_BIND_SERVICE
                - AUDIT_CONTROL
                - AUDIT_WRITE
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: rt-workstation-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: expose-ssh-2022
  annotations:
    metallb.universe.tf/address-pool: "rt-workstation"
    metallb.universe.tf/loadBalancerIPs: "10.0.40.147"
spec:
  allocateLoadBalancerNodePorts: true
  ports:
    - name: ssh
      protocol: TCP
      port: 2022
      targetPort: 2022
  type: LoadBalancer
  selector:
    app: rt-workstation-app